/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Aplikasi_yoscruizer;

import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author herry
 */
public class FormDataUser extends javax.swing.JFrame {

    /**
     * Creates new form FormDataJenis
     */
    public FormDataUser() {
        initComponents();
        tampilData("");
    }
    
    public void tampilData(String cari) {
        AksiDB aksidb = new AksiDB();
        String query;
        int i;
        DefaultTableModel dataModel = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int row, int column)
            {
                return false;
            }
        };
        dataModel.addColumn("No");
        dataModel.addColumn("Username");
        dataModel.addColumn("Password");
        dataModel.addColumn("Status");
        if(cari.equals("")){
            query ="SELECT * FROM t_user ORDER BY user_name";  
        }else{
            query ="SELECT * FROM t_user WHERE user_name LIKE '%" + 
                    textCari.getText() + "%' ORDER BY user_name";  
        }
        System.out.print(query);
        try{
            Class.forName("com.mysql.jdbc.Driver");
        }catch(Exception ex){
            System.out.println("Driver tidak ditemukan... " + ex);
        }
        i=1;
        try {
            aksidb.dbCon = DriverManager.getConnection(aksidb.dbURL, aksidb.username, aksidb.password);
            aksidb.stmt = aksidb.dbCon.createStatement();
            aksidb.rs = aksidb.stmt.executeQuery(query);
            while(aksidb.rs.next()){
                dataModel.addRow(new Object[]{
                    i,
                    aksidb.rs.getString("user_name"),
                    aksidb.rs.getString("user_pass"),
                    aksidb.rs.getString("user_tipe")
                    });
                i++;
            }           
        }catch (SQLException ex) {            
            System.out.println(ex);
        }finally{
            try {
                 aksidb.rs.close();
                 aksidb.stmt.close();
                 aksidb.dbCon.close();
             } catch (SQLException ex) {
                 Logger.getLogger(FormDataUser.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
        gridUser.setModel(dataModel);
    }
    
    public void hapus(String id) {
        AksiDB aksidb = new AksiDB();
        String query ="DELETE FROM t_user WHERE user_name = '" + id + "'";
        try{
            Class.forName("com.mysql.jdbc.Driver");
        }catch(Exception ex){
            System.out.println("Driver tidak ditemukan... " + ex);
        }   
        try {
            aksidb.dbCon = DriverManager.getConnection(aksidb.dbURL, aksidb.username, aksidb.password);
            aksidb.stmt = aksidb.dbCon.createStatement();
            aksidb.stmt.executeUpdate(query);
        } catch (SQLException ex) {
            System.out.println(ex);
        } finally{
            try {
                 aksidb.stmt.close();
                 aksidb.dbCon.close();
             } catch (SQLException ex) {
                 Logger.getLogger(FormDataUser.class.getName()).log(Level.SEVERE, null, ex);
             }
            textCari.setText("");
            tampilData("");
            JOptionPane.showMessageDialog(null,"Data Sudah Dihapus.", "Konfirmasi",
                    JOptionPane.INFORMATION_MESSAGE );
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        gridUser = new javax.swing.JTable();
        tombolTambah = new javax.swing.JButton();
        tombolEdit = new javax.swing.JButton();
        tombolHapus = new javax.swing.JButton();
        tombolKeluar = new javax.swing.JButton();
        tombolCari = new javax.swing.JButton();
        textCari = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistem Informasi Penjualan - Daftar Data User");
        setUndecorated(true);

        gridUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(gridUser);

        tombolTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Tambah.png"))); // NOI18N
        tombolTambah.setText("Tambah Data");
        tombolTambah.setFocusable(false);
        tombolTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tombolTambah.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tombolTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolTambahActionPerformed(evt);
            }
        });

        tombolEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Edit.png"))); // NOI18N
        tombolEdit.setText("Edit Data");
        tombolEdit.setFocusable(false);
        tombolEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tombolEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tombolEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolEditActionPerformed(evt);
            }
        });

        tombolHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Aplikasi_yoscruizer/Cancel.png"))); // NOI18N
        tombolHapus.setText("Hapus Data");
        tombolHapus.setFocusable(false);
        tombolHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tombolHapus.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tombolHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHapusActionPerformed(evt);
            }
        });

        tombolKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Keluar2.png"))); // NOI18N
        tombolKeluar.setText("Keluar");
        tombolKeluar.setFocusable(false);
        tombolKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tombolKeluar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tombolKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKeluarActionPerformed(evt);
            }
        });

        tombolCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/Cari2.png"))); // NOI18N
        tombolCari.setText("Cari");
        tombolCari.setFocusable(false);
        tombolCari.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tombolCari.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tombolCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tombolTambah)
                        .addGap(18, 18, 18)
                        .addComponent(textCari, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolCari, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tombolKeluar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tombolHapus)
                        .addGap(26, 26, 26)
                        .addComponent(tombolEdit))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tombolTambah, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(textCari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(tombolCari, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tombolEdit)
                    .addComponent(tombolHapus)
                    .addComponent(tombolKeluar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tombolCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolCariActionPerformed
        tampilData(textCari.getText().trim());
    }//GEN-LAST:event_tombolCariActionPerformed

    private void tombolTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolTambahActionPerformed
        FormUser formUser = new FormUser(this);
        formUser.setLocationRelativeTo(null); //membuat form center
        formUser.setAlwaysOnTop(true);
        formUser.setVisible(true);
    }//GEN-LAST:event_tombolTambahActionPerformed

    private void tombolKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKeluarActionPerformed
        new Penjualan().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_tombolKeluarActionPerformed

    private void tombolHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHapusActionPerformed
        int xPilih, xCol, xRow;
        String id;
        xCol = gridUser.getSelectedColumn();
        xRow = gridUser.getSelectedRow();
        id = gridUser.getValueAt(xRow,1).toString();
        Object[] pilihan = {"Tidak!","Iya, sangat yakin."};
        xPilih = JOptionPane.showOptionDialog(null,
                "Apakah Anda yakin akan menghapus data ini : " + "\n" +
                        "\t\t" + "Username = " + id + "\n",
                "Konfirmasi", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null,
                pilihan,
                pilihan[0]);
        if(xPilih==1){
            hapus(id);
        }
    }//GEN-LAST:event_tombolHapusActionPerformed

    private void tombolEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolEditActionPerformed
        String id;
        int xRow;
        xRow = gridUser.getSelectedRow();
        id = gridUser.getValueAt(xRow,1).toString();
        FormUser formUser = new FormUser(this, id);
        formUser.setLocationRelativeTo(null); //membuat form center
        formUser.setAlwaysOnTop(true);
        formUser.setVisible(true);
    }//GEN-LAST:event_tombolEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormDataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormDataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormDataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormDataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormDataUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gridUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField textCari;
    private javax.swing.JButton tombolCari;
    private javax.swing.JButton tombolEdit;
    private javax.swing.JButton tombolHapus;
    private javax.swing.JButton tombolKeluar;
    private javax.swing.JButton tombolTambah;
    // End of variables declaration//GEN-END:variables
}
